### ISSUE TITLE
got error on cameraId

### ISSUE THREAD

**Issue by rickvisual** [plluke/tof#1]
2019-12-09 19:12:13.790 17577-17577/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-12-09 19:12:13.790 17577-17577/? E/Zygote: accessInfo : 1
2019-12-09 19:12:14.009 17577-17577/com.example.tof E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tof, PID: 17577
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tof/com.example.tof.MainActivity}: java.lang.IllegalArgumentException: cameraId was null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7063)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.IllegalArgumentException: cameraId was null
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:617)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:544)
        at com.example.tof.Camera.openCamera(Camera.java:91)
        at com.example.tof.Camera.openFrontDepthCamera(Camera.java:50)
        at com.example.tof.MainActivity.onCreate(MainActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7063) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 

** cameraManager.getCameraIdList() returns null

Does this app need root privilege or some settings?**

**Comment by rickvisual** [comment]
It need android 10 to get depth data
